name: ci
on:
  #push:
    #branches: ['main']

  workflow_dispatch:
    inputs:
      run_test:
        description: "Which test to run"
        required: true
        type: choice
        options: [unit, integrations, all]
        default: all
        
        
        
env:
  passed: Passed ✅
  failed: Failed ❌
jobs:
  setup:
    # virtual machin linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # Checkar repository till mappen $GITHUB_WORKSPACE, så att workflow kan kommma åt koden.
        # Explanation: it bring my repot and added on this machin, so the rest of workflow can see it.
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: check python
        run: python --version

      - name: Passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: Failed
        if: ${{ failure() }}
        run: echo "$failed"

      - name: requirements install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: failed
        if: ${{ failure() }}
        run: echo "$failed"

  unit-test:
    if: ${{ github.event.inputs.run_test  == 'unit' ||  github.event.inputs.run_test == 'all' }}
    needs: setup
    name: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: ínstall requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: unit test
        run: pytest -q weather_app/test_enhet.py
       

      - name: Passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: Failed
        if: ${{ failure() }}
        run: echo "$failed"


  integrations-test:
    if: ${{ github.events.inputs.run_test == 'integrations' ||  github.event.inputs.run_test == 'all'  }}
    needs: [setup]
    name: integrations-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: integration test
        run: pytest -q weather_app/test_integration.py

      - name: passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: failed
        if: ${{ failure() }}
        run: echo "$failed"
