name: ci
on:
  workflow_dispatch:
    inputs:
      show_log:
        description: "If you want to see the log"
        type: choice
        options: ["true", "false"]
        default: "false"
               
env:
  passed: Passed ✅
  failed: Failed ❌
jobs:
  setup:
    # virtual machin linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # Checkar repository till mappen $GITHUB_WORKSPACE, så att workflow kan kommma åt koden.
        # Explanation: it bring my repot and added on this machin, so the rest of workflow can see it.
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: check python
        run: python --version

      - name: Passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: Failed
        if: ${{ failure() }}
        run: echo "$failed"

      - name: requirements install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Passed
        if: ${{ success() }}
        run: echo "install  $passed"

      - name: failed
        if: ${{ failure() }}
        run: echo "install $failed"

  unit-test:
    needs: setup
    name: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: ínstall requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: unit test without log
        if: ${{ github.event.inputs.show_log == 'false' }}
        run: pytest -q weather_app/test_enhet.py
                     
        
      - name: uni test with log in artifact
        if: ${{ github.event.inputs.show_log == 'true' }}
        shell: bash
        run: |
          pytest -q weather_app/test_enhet.py > unit-test-log.txt
          
      - name: upload unitest in artifacts
        if: ${{ failure() && github.event.inputs.show_log == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-log 
          path: unit-test-log.txt
          
      - name: Passed
        if: ${{ success() }}
        run: echo "unit test $passed"

      - name: Failed
        if: ${{ failure() }}
        run: echo "unit test $failed"
            
  integrations-test:
    needs: [setup, unit-test]
    name: integrations-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: integration test without log in artifact
        if: ${{ github.event.inputs.show_log == 'false'
        run: pytest -q weather_app/test_integration.py

      - name: integration test with log in artifact
        if: ${{ github.event.inputs.show_log == 'true' }}
        shell: bash
        run: |
          pytest -q waether_app/test_integration.py > integration-test-log.txt

      - name: upload integration test in artifact
        if: ${{ failure() && github.event.inputs.show_log == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-log
          path: integration-test-log.txt
          
      - name: passed
        if: ${{ success() }}
        run: echo "integration test $passed"

      - name: failed
        if: ${{ failure() }}
        run: echo "integration test $failed"
