name: dev
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      show_log:
        description: "Create a logging in artifact. Chooce between true/false"
        type: choice 
        options: ["true", "false"]
        default: "false"
               

env:
  passed: Passed ✅
  failed: Failed ❌
  repot: marcusardenstedt/weather-app
jobs:
  setup:
    # virtual machin linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # Checkar repository till mappen $GITHUB_WORKSPACE, så att workflow kan kommma åt koden.
        # Explanation: it bring my repot and added on this machin, so the rest of workflow can see it.
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: check python version
        run: python --version

      - name: Python passed
        if: ${{ success() }}
        run: echo "$passed"

      - name: Python failed
        if: ${{ failure() }}
        run: echo "$failed"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: install passed
        if: ${{ success() }}
        run: echo "install  $passed"

      - name: Install failed
        if: ${{ failure() }}
        run: echo "$failed"

  unit-test:
    needs: setup
    name: unit-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: ínstall requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: unit test without log
        if: ${{ github.event.inputs.show_log == 'false' }}
        run: pytest -q weather_app/test_enhet.py
                     
        # When the parameter is choocen true, shell: bash a bash command will run it.
        # all text that commando type out writes in en txt file.
      - name: unit test with log in artifact
        if: ${{ github.event.inputs.show_log == 'true' }}
        shell: bash
        run: pytest -q weather_app/test_enhet.py > unit-test-log.txt

        # if true, the file upload as a artifacts with name unit-test-log
      - name: upload unitest in artifacts
        if: ${{ failure() && github.event.inputs.show_log == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-log 
          path: unit-test-log.txt
          
      - name: Passed
        if: ${{ success() }}
        run: echo "unit test $passed"

      - name: Failed
        if: ${{ failure() }}
        run: echo "unit test $failed"
            
  integrations-test:
    needs: [setup, unit-test]
    name: integrations-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: installing requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: integration test with out log in artifact
        if: ${{ github.event.inputs.show_log == 'false' }}
        run: pytest -q weather_app/test_integration.py

        # When the parameter is chooce true, shell: bash is what it run with bash command.
        # all text that commando commando type out writes in en txt file.
      - name: integration test with log in artifact
        if: ${{ github.event.inputs.show_log == 'true' }}
        shell: bash
        run: pytest -q weather_app/test_integration.py > integration-test-log.txt
        
        # if true, the file upload as a artifacts with name integration-test-log
      - name: upload integration test in artifact
        if: ${{ failure() && github.event.inputs.show_log == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-log
          path: integration-test-log.txt
          
      - name: passed
        if: ${{ success() }}
        run: echo "integration test $passed"

      - name: failed
        if: ${{ failure() }}
        run: echo "integration test $failed"


  build-and-push:
    needs: [setup, unit-test, integrations-test]
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v5
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_WEATHER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_WEATHER }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ${{ env.repot }}:latest
            ${{ env.repot }}:v${{ github.run_number }}
