name: docker image

on: 
  workflow_run:
    workflows: [ci]
    types: [completed]

jobs: 
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github_event.workflow_run.conclusion == 'ci' }}
    steps:
      - run: echo "Triggering workflow passed"

      - name: check out repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_WEATHER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD_WEATHER }}

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            marcusardenstedt/weather-app-de24:latest
            marcusardenstedt/weather-app-de24:1.5
         
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github_event.workflow_run.conclusion == 'ci' }}
    steps:
      - run: echo "Triggering workflow failed"

      
