name: create branch

on: 
  push: 
    branches: [features]
      

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: printout
        run: |
          echo "# Creating new branch"
          echo "checking that's everthing is okej"

          
